# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/SICT/Do_An/4/ui/dacs4.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(350, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(350, 450))
        Form.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                           "font: 12pt \"Ubuntu Mono\";\n"
                           "color: rgb(48, 10, 36);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.grb_to = QtWidgets.QGroupBox(Form)
        self.grb_to.setStyleSheet("#grb_to{\n"
                                  "border-radius: 5px;\n"
                                  "border: 2px solid #300a24;\n"
                                  "background-color: rgb(255, 255, 255);\n"
                                  "padding-top: 10px;\n"
                                  "}")
        self.grb_to.setObjectName("grb_to")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grb_to)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_connect = QtWidgets.QPushButton(self.grb_to)
        self.btn_connect.setStyleSheet("border-radius: 5px;\n"
                                       "border: 2px solid #300a24;\n"
                                       "background-color: rgb(255, 255, 255);")
        self.btn_connect.setObjectName("btn_connect")
        self.gridLayout_2.addWidget(self.btn_connect, 1, 5, 1, 1)
        self.txt_host = QtWidgets.QLineEdit(self.grb_to)
        self.txt_host.setStyleSheet("border-radius: 5px;\n"
                                    "border: 2px solid #300a24;\n"
                                    "background-color: rgb(255, 255, 255);")
        self.txt_host.setObjectName("txt_host")
        self.gridLayout_2.addWidget(self.txt_host, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.grb_to)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.grb_to)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.txt_port = QtWidgets.QLineEdit(self.grb_to)
        self.txt_port.setStyleSheet("border-radius: 5px;\n"
                                    "border: 2px solid #300a24;\n"
                                    "background-color: rgb(255, 255, 255);")
        self.txt_port.setObjectName("txt_port")
        self.gridLayout_2.addWidget(self.txt_port, 1, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.grb_to)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 4, 1, 1)
        self.gridLayout.addWidget(self.grb_to, 2, 1, 1, 4)
        self.grb_from = QtWidgets.QGroupBox(Form)
        self.grb_from.setStyleSheet("#grb_from{\n"
                                    "border-radius: 5px;\n"
                                    "border: 2px solid #300a24;\n"
                                    "background-color: rgb(255, 255, 255);\n"
                                    "padding-top: 10px;\n"
                                    "}")
        self.grb_from.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.grb_from.setObjectName("grb_from")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.grb_from)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.grb_from)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.grb_from)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.txt_comp_name = QtWidgets.QLineEdit(self.grb_from)
        self.txt_comp_name.setEnabled(False)
        self.txt_comp_name.setStyleSheet("border-radius: 5px;\n"
                                         "border: 2px solid #300a24;\n"
                                         "background-color: rgb(255, 255, 255);")
        self.txt_comp_name.setObjectName("txt_comp_name")
        self.gridLayout_3.addWidget(self.txt_comp_name, 0, 1, 1, 2)
        self.txt_address = QtWidgets.QLineEdit(self.grb_from)
        self.txt_address.setEnabled(False)
        self.txt_address.setStyleSheet("border-radius: 5px;\n"
                                       "border: 2px solid #300a24;\n"
                                       "background-color: rgb(255, 255, 255);")
        self.txt_address.setObjectName("txt_address")
        self.gridLayout_3.addWidget(self.txt_address, 1, 1, 1, 2)
        self.gridLayout.addWidget(self.grb_from, 1, 1, 1, 4)
        self.grb_friends = QtWidgets.QGroupBox(Form)
        self.grb_friends.setStyleSheet("#grb_friends{\n"
                                       "border-radius: 5px;\n"
                                       "border: 2px solid #300a24;\n"
                                       "background-color: rgb(255, 255, 255);\n"
                                       "padding-top: 10px;\n"
                                       "}")
        self.grb_friends.setObjectName("grb_friends")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.grb_friends)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txt_friends = QtWidgets.QTextEdit(self.grb_friends)
        self.txt_friends.setEnabled(True)
        self.txt_friends.setStyleSheet("border: none;")
        self.txt_friends.setPlaceholderText("")
        self.txt_friends.setObjectName("txt_friends")
        self.verticalLayout.addWidget(self.txt_friends)
        self.gridLayout.addWidget(self.grb_friends, 3, 3, 1, 2)
        self.btn_send = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_send.sizePolicy().hasHeightForWidth())
        self.btn_send.setSizePolicy(sizePolicy)
        self.btn_send.setMaximumSize(QtCore.QSize(50, 25))
        self.btn_send.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border: 2px solid #300a24;\n"
                                    "border-radius: 5px;")
        self.btn_send.setObjectName("btn_send")
        self.gridLayout.addWidget(self.btn_send, 4, 4, 1, 1)
        self.txt_msg = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_msg.sizePolicy().hasHeightForWidth())
        self.txt_msg.setSizePolicy(sizePolicy)
        self.txt_msg.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txt_msg.setStyleSheet("border-radius: 5px;\n"
                                   "border: 2px solid #300a24;\n"
                                   "background-color: rgb(255, 255, 255);")
        self.txt_msg.setText("")
        self.txt_msg.setObjectName("txt_msg")
        self.gridLayout.addWidget(self.txt_msg, 4, 1, 1, 2)
        self.btn_file = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_file.sizePolicy().hasHeightForWidth())
        self.btn_file.setSizePolicy(sizePolicy)
        self.btn_file.setMaximumSize(QtCore.QSize(50, 25))
        self.btn_file.setStyleSheet("border-radius: 5px;\n"
                                    "border: 2px solid #300a24;\n"
                                    "background-color: rgb(255, 255, 255);")
        self.btn_file.setObjectName("btn_file")
        self.gridLayout.addWidget(self.btn_file, 4, 3, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("#frame {\n"
                                 "border-radius: 5px;\n"
                                 "border: 2px solid #300a24;\n"
                                 "background-color: rgb(255, 255, 255);\n"
                                 "padding-top: 10px;\n"
                                 "}\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txt_chat = QtWidgets.QTextEdit(self.frame)
        self.txt_chat.setStyleSheet("border: none;")
        self.txt_chat.setObjectName("txt_chat")
        self.verticalLayout_2.addWidget(self.txt_chat)
        self.gridLayout.addWidget(self.frame, 3, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Node"))
        self.grb_to.setTitle(_translate("Form", "To"))
        self.btn_connect.setText(_translate("Form", "Add Friend"))
        self.label.setText(_translate("Form", "Host:"))
        self.label_2.setText(_translate("Form", "Port:"))
        self.grb_from.setTitle(_translate("Form", "From"))
        self.label_3.setText(_translate("Form", "Computer Name:"))
        self.label_4.setText(_translate("Form", "Address:"))
        self.grb_friends.setTitle(_translate("Form", "Friends"))
        self.btn_send.setText(_translate("Form", "send"))
        self.btn_file.setText(_translate("Form", "file"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    from controller import Controller, Server

    server = Server(ui)
    server.start()
    ctrl = Controller(ui)
    ctrl.event_catch()
    sys.exit(app.exec_())
